name: Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: make -f Makefile.unx
